### ISSUE TITLE
Not working in Python 3

### ISSUE THREAD

**Issue by Zerokami** [erikriver/opengraph#32]
It works when I run with Python 2, but when I run with Python 3 I get the following error.

```
Traceback (most recent call last):
  File "og.py", line 9, in <module>
    import opengraph
  File "/usr/local/lib/python3.5/dist-packages/opengraph/__init__.py", line 1, in <module>
    from opengraph import OpenGraph
```

**Comment by jjdelc** [comment]
This needs a new release, current code in master branch is working correctly. The 0.5 release doesn't have the fixes.

You can get by installing from current master checkout.

**Comment by fixmycode** [comment]
seems like the author uploaded the python 3 version with another package name, it's on PyPI as [opengraph_py3](https://pypi.org/project/opengraph_py3/)

    pip install opengraph_py3

**Comment by advance512** [comment]
4.5 years ago. I think that this codebase is deprecated.
Better use:
https://github.com/topicaxis/opengraph
or:
https://github.com/ji3g4m6zo6/opengraph_py3-0.71
or even:
https://github.com/jvanasco/metadata_parser
